static CHARACTER_SIZE: usize = 5 * 7;

static UNKNOWN: [bool; CHARACTER_SIZE] = [
    false, false, false, false, false,
    false, true,  true,  true,  false,
    false, true,  false, true,  false,
    false, true,  false, true,  false,
    false, true,  false, true,  false,
    false, true,  true,  true,  false,
    false, false, false, false, false,
];

pub static CHARACTERS: [[bool; CHARACTER_SIZE]; 255] = [
    // these characters are empty characters for padding, you're allowed to add them, it's so it lines up with vga
    [false; CHARACTER_SIZE], UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,

    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,

    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,

    UNKNOWN, UNKNOWN, [false; CHARACTER_SIZE], 
    
    [ // character !
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
    ],
    [ // character "
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
    ],
    
    UNKNOWN, UNKNOWN,

    [ // character %
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        false, true,  false, true,  false,
    ],
    
    UNKNOWN,

    [ // character '
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
    ],
    [ // character (
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  true,  false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  true,  false, false,
        false, false, true,  true,  false,
    ],
    [ // character )
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, false, true,  true,  false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, false, true,  true,  false,
        false, true,  true,  false, false,
    ],

    UNKNOWN, 
    [ // character +
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  true,  true,  false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, false, false, false,
    ],
    [ // character ,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character -
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        true,  true,  true,  true,  false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
    ],
    [ // character .
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
    ],
    [ // character /
        false, false, false, false, false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
    ],
    [ // character 0
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
    ],
    [ // character 1
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  true,  true,  false,
    ],
    [ // character 2
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
    ],
    [ // character 3
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, false, false, true,  false,
        false, true,  true,  false, false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character 4
        false, false, false, false, false,
        false, true,  true,  false, false,
        true,  false, true,  false, false,
        true,  false, true,  false, false,
        true,  true,  true,  true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character 5
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, true,  true,  false, false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character 6
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
    ],
    [ // character 7
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character 8
        false, false, false, false, false,
        false, true,  true,  false, false,
        true,  false, false, true,  false,
        false, true,  true,  false, false,
        true,  false, false, true,  false,
        true,  false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character 9
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character :
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, false, false, false,
    ],
    UNKNOWN, 
    [ // character <
        false, false, false, false, false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        false, false, true,  false, false,
        false, false, false, true,  false,
        false, false, false, false, false,
    ],
    [ // character =
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, false, false, false, false,
        false, false, false, false, false,
    ],
    [ // character >
        false, false, false, false, false,
        false, true,  false, false, false,
        false, false, true,  false, false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        false, false, false, false, false,
    ],
    [ // character .
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  false, true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
    ],
    
    UNKNOWN,

    [ // character A
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ], 
    [ // character B
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
    ],
    [ // character C
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, false, true,  true,  false,
    ],
    [ // character D
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character E
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
    ],
    [ // character F
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
    ],
    [ // character G
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
    ],
    [ // character H
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character I
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  true,  true,  false,
    ],
    [ // character J
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  true,  false, false,
    ],
    [ // character K
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character L
        false, false, false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
    ],
    [ // character M
        false, false, false, false, false,
        true, true,   false, true,  false,
        true, false,  true,  false, true,
        true, false,  true,  false, true,
        true, false,  true,  false, true,
        true, false,  true,  false, true,
        true, false,  true,  false, true,
    ],
    [ // character N
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character O
        false, false, false, false, false,
        false, true,  true,  false, false,
        true,  false, false, true,  false,
        true,  false, false, true,  false,
        true,  false, false, true,  false,
        true,  false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character P
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
    ],
    [ // character Q
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, true,
    ],
    [ // character R
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character S
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, false, false,
        false, true,  true,  false, false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character T
        false, false, false, false, false,
        true,  true,  true,  true,  true,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character U
        false, false, false, false, false,
        false, true,  false, true, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character V
        false, false, false, false, false,
        false, true,  false, true, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
    ],
    [ // character W
        false, false, false, false, false,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        false, true,  false, true,  false,
    ],
    [ // character X
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character Y
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character Z
        false, false, false, false, false,
        true,  true,  true,  true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        true,  false, false, false, false,
        true,  true,  true,  true,  false,
    ],
    [ // character [
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  true,  false,
    ],
    UNKNOWN,
    [ // character ]
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  true,  false, false,
    ],

    UNKNOWN, 

    [ // character ]
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        true,  true,  true,  true,  false,
    ],
    
    UNKNOWN,
    
    [ // character a
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  true, 
    ], 
    [ // character b
        false, false, false, false, false,
        false, true, false,  false, false,
        false, true,  false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
    ],
    [ // character c
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, false, true,  true,  false,
    ],
    [ // character d
        false, false, false, false, false,
        false, false, false, true,  false,
        false, false, false, true,  false,
        false, false, true,  true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
    ],
    [ // character e
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
        false, true,  false, false, false,
        false, false, true,  true,  false,
    ],
    [ // character f
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, false, true,  false, false,
        false, true,  true,  true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character g
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, true,  false,
        false, true,  true,  true,  false,
        false, false, false, true,  false,
        false, true,  true,  true,  false,
    ],
    [ // character h
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character i
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character j
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, true,  true,  false, false,
    ],
    [ // character k
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, false, false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character l
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  true,  false,
    ],
    [ // character m
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        true,  true,  false, true,  false,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
    ],
    [ // character n
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character o
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  true,  false, false,
        true,  false, false, true,  false,
        true,  false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character p
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  true,  false, false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
    ],
    [ // character q
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, true,  false,
        false, false, true,  true,  false,
        false, false, false, true,  false,
        false, false, false, true,  false,
    ],
    [ // character r
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
        false, true,  false, false, false,
    ],
    [ // character s
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  true,  false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
        false, false, false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character t
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, true,  false, false,
        false, true,  true,  true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  true,  false,
    ],
    [ // character u
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  true,  false, false,
    ],
    [ // character v
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
    ],
    [ // character w
        false, false, false, false, false,
        false, false, false, false, false,
        false, false, false, false, false,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        true,  false, true,  false, true,
        false, true,  false, true,  false,
    ],
    [ // character x
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
    ],
    [ // character y
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  false, true,  false,
        false, true,  false, true,  false,
        false, false, true,  false, false,
        false, false, true,  false, false,
        false, false, true,  false, false,
    ],
    [ // character z
        false, false, false, false, false,
        false, false, false, false, false,
        false, true,  true,  true,  false,
        false, false, false, true,  false,
        false, false, true,  false, false,
        false, true,  false, false, false,
        false, true,  true,  true,  false,
    ],

    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN,
    UNKNOWN, UNKNOWN
];